/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CharactersCharacterIdKillmailsRecentGetInner,
    CharactersCharacterIdKillmailsRecentGetInnerFromJSON,
    CharactersCharacterIdKillmailsRecentGetInnerToJSON,
} from '../models/CharactersCharacterIdKillmailsRecentGetInner';
import {
    type EsiError,
    EsiErrorFromJSON,
    EsiErrorToJSON,
} from '../models/EsiError';
import {
    type KillmailsKillmailIdKillmailHashGet,
    KillmailsKillmailIdKillmailHashGetFromJSON,
    KillmailsKillmailIdKillmailHashGetToJSON,
} from '../models/KillmailsKillmailIdKillmailHashGet';

export interface GetCharactersCharacterIdKillmailsRecentRequest {
    characterId: number;
    xCompatibilityDate: GetCharactersCharacterIdKillmailsRecentXCompatibilityDateEnum;
    page?: number;
    acceptLanguage?: GetCharactersCharacterIdKillmailsRecentAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface GetCorporationsCorporationIdKillmailsRecentRequest {
    corporationId: number;
    xCompatibilityDate: GetCorporationsCorporationIdKillmailsRecentXCompatibilityDateEnum;
    page?: number;
    acceptLanguage?: GetCorporationsCorporationIdKillmailsRecentAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface GetKillmailsKillmailIdKillmailHashRequest {
    killmailHash: string;
    killmailId: number;
    xCompatibilityDate: GetKillmailsKillmailIdKillmailHashXCompatibilityDateEnum;
    acceptLanguage?: GetKillmailsKillmailIdKillmailHashAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

/**
 * 
 */
export class KillmailsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getCharactersCharacterIdKillmailsRecent without sending the request
     */
    async getCharactersCharacterIdKillmailsRecentRequestOpts(requestParameters: GetCharactersCharacterIdKillmailsRecentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['characterId'] == null) {
            throw new runtime.RequiredError(
                'characterId',
                'Required parameter "characterId" was null or undefined when calling getCharactersCharacterIdKillmailsRecent().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCharactersCharacterIdKillmailsRecent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-killmails.read_killmails.v1"]);
        }


        let urlPath = `/characters/{character_id}/killmails/recent`;
        urlPath = urlPath.replace('{character_id}', encodeURIComponent(String(requestParameters['characterId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return a list of a character\'s kills and losses going back 90 days
     * Get a character\'s recent kills and losses
     */
    async getCharactersCharacterIdKillmailsRecentRaw(requestParameters: GetCharactersCharacterIdKillmailsRecentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CharactersCharacterIdKillmailsRecentGetInner>>> {
        const requestOptions = await this.getCharactersCharacterIdKillmailsRecentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CharactersCharacterIdKillmailsRecentGetInnerFromJSON));
    }

    /**
     * Return a list of a character\'s kills and losses going back 90 days
     * Get a character\'s recent kills and losses
     */
    async getCharactersCharacterIdKillmailsRecent(requestParameters: GetCharactersCharacterIdKillmailsRecentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CharactersCharacterIdKillmailsRecentGetInner>> {
        const response = await this.getCharactersCharacterIdKillmailsRecentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCorporationsCorporationIdKillmailsRecent without sending the request
     */
    async getCorporationsCorporationIdKillmailsRecentRequestOpts(requestParameters: GetCorporationsCorporationIdKillmailsRecentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['corporationId'] == null) {
            throw new runtime.RequiredError(
                'corporationId',
                'Required parameter "corporationId" was null or undefined when calling getCorporationsCorporationIdKillmailsRecent().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCorporationsCorporationIdKillmailsRecent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-killmails.read_corporation_killmails.v1"]);
        }


        let urlPath = `/corporations/{corporation_id}/killmails/recent`;
        urlPath = urlPath.replace('{corporation_id}', encodeURIComponent(String(requestParameters['corporationId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a list of a corporation\'s kills and losses going back 90 days
     * Get a corporation\'s recent kills and losses
     */
    async getCorporationsCorporationIdKillmailsRecentRaw(requestParameters: GetCorporationsCorporationIdKillmailsRecentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CharactersCharacterIdKillmailsRecentGetInner>>> {
        const requestOptions = await this.getCorporationsCorporationIdKillmailsRecentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CharactersCharacterIdKillmailsRecentGetInnerFromJSON));
    }

    /**
     * Get a list of a corporation\'s kills and losses going back 90 days
     * Get a corporation\'s recent kills and losses
     */
    async getCorporationsCorporationIdKillmailsRecent(requestParameters: GetCorporationsCorporationIdKillmailsRecentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CharactersCharacterIdKillmailsRecentGetInner>> {
        const response = await this.getCorporationsCorporationIdKillmailsRecentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getKillmailsKillmailIdKillmailHash without sending the request
     */
    async getKillmailsKillmailIdKillmailHashRequestOpts(requestParameters: GetKillmailsKillmailIdKillmailHashRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['killmailHash'] == null) {
            throw new runtime.RequiredError(
                'killmailHash',
                'Required parameter "killmailHash" was null or undefined when calling getKillmailsKillmailIdKillmailHash().'
            );
        }

        if (requestParameters['killmailId'] == null) {
            throw new runtime.RequiredError(
                'killmailId',
                'Required parameter "killmailId" was null or undefined when calling getKillmailsKillmailIdKillmailHash().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getKillmailsKillmailIdKillmailHash().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }


        let urlPath = `/killmails/{killmail_id}/{killmail_hash}`;
        urlPath = urlPath.replace('{killmail_hash}', encodeURIComponent(String(requestParameters['killmailHash'])));
        urlPath = urlPath.replace('{killmail_id}', encodeURIComponent(String(requestParameters['killmailId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return a single killmail from its ID and hash
     * Get a single killmail
     */
    async getKillmailsKillmailIdKillmailHashRaw(requestParameters: GetKillmailsKillmailIdKillmailHashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KillmailsKillmailIdKillmailHashGet>> {
        const requestOptions = await this.getKillmailsKillmailIdKillmailHashRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KillmailsKillmailIdKillmailHashGetFromJSON(jsonValue));
    }

    /**
     * Return a single killmail from its ID and hash
     * Get a single killmail
     */
    async getKillmailsKillmailIdKillmailHash(requestParameters: GetKillmailsKillmailIdKillmailHashRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KillmailsKillmailIdKillmailHashGet> {
        const response = await this.getKillmailsKillmailIdKillmailHashRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetCharactersCharacterIdKillmailsRecentXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetCharactersCharacterIdKillmailsRecentXCompatibilityDateEnum = typeof GetCharactersCharacterIdKillmailsRecentXCompatibilityDateEnum[keyof typeof GetCharactersCharacterIdKillmailsRecentXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCharactersCharacterIdKillmailsRecentAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCharactersCharacterIdKillmailsRecentAcceptLanguageEnum = typeof GetCharactersCharacterIdKillmailsRecentAcceptLanguageEnum[keyof typeof GetCharactersCharacterIdKillmailsRecentAcceptLanguageEnum];
/**
 * @export
 */
export const GetCorporationsCorporationIdKillmailsRecentXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetCorporationsCorporationIdKillmailsRecentXCompatibilityDateEnum = typeof GetCorporationsCorporationIdKillmailsRecentXCompatibilityDateEnum[keyof typeof GetCorporationsCorporationIdKillmailsRecentXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCorporationsCorporationIdKillmailsRecentAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCorporationsCorporationIdKillmailsRecentAcceptLanguageEnum = typeof GetCorporationsCorporationIdKillmailsRecentAcceptLanguageEnum[keyof typeof GetCorporationsCorporationIdKillmailsRecentAcceptLanguageEnum];
/**
 * @export
 */
export const GetKillmailsKillmailIdKillmailHashXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetKillmailsKillmailIdKillmailHashXCompatibilityDateEnum = typeof GetKillmailsKillmailIdKillmailHashXCompatibilityDateEnum[keyof typeof GetKillmailsKillmailIdKillmailHashXCompatibilityDateEnum];
/**
 * @export
 */
export const GetKillmailsKillmailIdKillmailHashAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetKillmailsKillmailIdKillmailHashAcceptLanguageEnum = typeof GetKillmailsKillmailIdKillmailHashAcceptLanguageEnum[keyof typeof GetKillmailsKillmailIdKillmailHashAcceptLanguageEnum];
