/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type EsiError,
    EsiErrorFromJSON,
    EsiErrorToJSON,
} from '../models/EsiError';
import {
    type MetaChangelog,
    MetaChangelogFromJSON,
    MetaChangelogToJSON,
} from '../models/MetaChangelog';
import {
    type MetaCompatibilityDates,
    MetaCompatibilityDatesFromJSON,
    MetaCompatibilityDatesToJSON,
} from '../models/MetaCompatibilityDates';

export interface GetMetaChangelogRequest {
    xCompatibilityDate: GetMetaChangelogXCompatibilityDateEnum;
    acceptLanguage?: GetMetaChangelogAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface GetMetaCompatibilityDatesRequest {
    xCompatibilityDate: GetMetaCompatibilityDatesXCompatibilityDateEnum;
    acceptLanguage?: GetMetaCompatibilityDatesAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

/**
 * 
 */
export class MetaApi extends runtime.BaseAPI {

    /**
     * Creates request options for getMetaChangelog without sending the request
     */
    async getMetaChangelogRequestOpts(requestParameters: GetMetaChangelogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getMetaChangelog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }


        let urlPath = `/meta/changelog`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the changelog of this API.
     * Get changelog
     */
    async getMetaChangelogRaw(requestParameters: GetMetaChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetaChangelog>> {
        const requestOptions = await this.getMetaChangelogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaChangelogFromJSON(jsonValue));
    }

    /**
     * Get the changelog of this API.
     * Get changelog
     */
    async getMetaChangelog(requestParameters: GetMetaChangelogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetaChangelog> {
        const response = await this.getMetaChangelogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMetaCompatibilityDates without sending the request
     */
    async getMetaCompatibilityDatesRequestOpts(requestParameters: GetMetaCompatibilityDatesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getMetaCompatibilityDates().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }


        let urlPath = `/meta/compatibility-dates`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a list of compatibility dates.
     * Get compatibility dates
     */
    async getMetaCompatibilityDatesRaw(requestParameters: GetMetaCompatibilityDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetaCompatibilityDates>> {
        const requestOptions = await this.getMetaCompatibilityDatesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaCompatibilityDatesFromJSON(jsonValue));
    }

    /**
     * Get a list of compatibility dates.
     * Get compatibility dates
     */
    async getMetaCompatibilityDates(requestParameters: GetMetaCompatibilityDatesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetaCompatibilityDates> {
        const response = await this.getMetaCompatibilityDatesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetMetaChangelogXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetMetaChangelogXCompatibilityDateEnum = typeof GetMetaChangelogXCompatibilityDateEnum[keyof typeof GetMetaChangelogXCompatibilityDateEnum];
/**
 * @export
 */
export const GetMetaChangelogAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetMetaChangelogAcceptLanguageEnum = typeof GetMetaChangelogAcceptLanguageEnum[keyof typeof GetMetaChangelogAcceptLanguageEnum];
/**
 * @export
 */
export const GetMetaCompatibilityDatesXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetMetaCompatibilityDatesXCompatibilityDateEnum = typeof GetMetaCompatibilityDatesXCompatibilityDateEnum[keyof typeof GetMetaCompatibilityDatesXCompatibilityDateEnum];
/**
 * @export
 */
export const GetMetaCompatibilityDatesAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetMetaCompatibilityDatesAcceptLanguageEnum = typeof GetMetaCompatibilityDatesAcceptLanguageEnum[keyof typeof GetMetaCompatibilityDatesAcceptLanguageEnum];
