/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CharactersCharacterIdAttributesGet,
    CharactersCharacterIdAttributesGetFromJSON,
    CharactersCharacterIdAttributesGetToJSON,
} from '../models/CharactersCharacterIdAttributesGet';
import {
    type CharactersSkillqueueSkill,
    CharactersSkillqueueSkillFromJSON,
    CharactersSkillqueueSkillToJSON,
} from '../models/CharactersSkillqueueSkill';
import {
    type CharactersSkills,
    CharactersSkillsFromJSON,
    CharactersSkillsToJSON,
} from '../models/CharactersSkills';
import {
    type EsiError,
    EsiErrorFromJSON,
    EsiErrorToJSON,
} from '../models/EsiError';

export interface GetCharactersCharacterIdAttributesRequest {
    characterId: number;
    xCompatibilityDate: GetCharactersCharacterIdAttributesXCompatibilityDateEnum;
    acceptLanguage?: GetCharactersCharacterIdAttributesAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface GetCharactersCharacterIdSkillqueueRequest {
    characterId: number;
    xCompatibilityDate: GetCharactersCharacterIdSkillqueueXCompatibilityDateEnum;
    acceptLanguage?: GetCharactersCharacterIdSkillqueueAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface GetCharactersCharacterIdSkillsRequest {
    characterId: number;
    xCompatibilityDate: GetCharactersCharacterIdSkillsXCompatibilityDateEnum;
    acceptLanguage?: GetCharactersCharacterIdSkillsAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

/**
 * 
 */
export class SkillsApi extends runtime.BaseAPI {

    /**
     * Creates request options for getCharactersCharacterIdAttributes without sending the request
     */
    async getCharactersCharacterIdAttributesRequestOpts(requestParameters: GetCharactersCharacterIdAttributesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['characterId'] == null) {
            throw new runtime.RequiredError(
                'characterId',
                'Required parameter "characterId" was null or undefined when calling getCharactersCharacterIdAttributes().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCharactersCharacterIdAttributes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-skills.read_skills.v1"]);
        }


        let urlPath = `/characters/{character_id}/attributes`;
        urlPath = urlPath.replace('{character_id}', encodeURIComponent(String(requestParameters['characterId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return attributes of a character
     * Get character attributes
     */
    async getCharactersCharacterIdAttributesRaw(requestParameters: GetCharactersCharacterIdAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharactersCharacterIdAttributesGet>> {
        const requestOptions = await this.getCharactersCharacterIdAttributesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CharactersCharacterIdAttributesGetFromJSON(jsonValue));
    }

    /**
     * Return attributes of a character
     * Get character attributes
     */
    async getCharactersCharacterIdAttributes(requestParameters: GetCharactersCharacterIdAttributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CharactersCharacterIdAttributesGet> {
        const response = await this.getCharactersCharacterIdAttributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCharactersCharacterIdSkillqueue without sending the request
     */
    async getCharactersCharacterIdSkillqueueRequestOpts(requestParameters: GetCharactersCharacterIdSkillqueueRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['characterId'] == null) {
            throw new runtime.RequiredError(
                'characterId',
                'Required parameter "characterId" was null or undefined when calling getCharactersCharacterIdSkillqueue().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCharactersCharacterIdSkillqueue().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-skills.read_skillqueue.v1"]);
        }


        let urlPath = `/characters/{character_id}/skillqueue`;
        urlPath = urlPath.replace('{character_id}', encodeURIComponent(String(requestParameters['characterId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List the configured skill queue for the given character.  Entries that have their finish time in the past are completed, but aren\'t updated in the \"/skills\" route yet. This will happen the next time the character logs in.
     * Get character\'s skill queue
     */
    async getCharactersCharacterIdSkillqueueRaw(requestParameters: GetCharactersCharacterIdSkillqueueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CharactersSkillqueueSkill>>> {
        const requestOptions = await this.getCharactersCharacterIdSkillqueueRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CharactersSkillqueueSkillFromJSON));
    }

    /**
     * List the configured skill queue for the given character.  Entries that have their finish time in the past are completed, but aren\'t updated in the \"/skills\" route yet. This will happen the next time the character logs in.
     * Get character\'s skill queue
     */
    async getCharactersCharacterIdSkillqueue(requestParameters: GetCharactersCharacterIdSkillqueueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CharactersSkillqueueSkill>> {
        const response = await this.getCharactersCharacterIdSkillqueueRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCharactersCharacterIdSkills without sending the request
     */
    async getCharactersCharacterIdSkillsRequestOpts(requestParameters: GetCharactersCharacterIdSkillsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['characterId'] == null) {
            throw new runtime.RequiredError(
                'characterId',
                'Required parameter "characterId" was null or undefined when calling getCharactersCharacterIdSkills().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling getCharactersCharacterIdSkills().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-skills.read_skills.v1"]);
        }


        let urlPath = `/characters/{character_id}/skills`;
        urlPath = urlPath.replace('{character_id}', encodeURIComponent(String(requestParameters['characterId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all trained skills for the given character.  Skills returned by this route can be out-of-date if the character hasn\'t logged in since one or more skills completed training. Use the /skillqueue route to check for skills that completed training. Entries that are in the past need to be applied on top of this list to get an accurate view of the character\'s current skills.
     * Get character skills
     */
    async getCharactersCharacterIdSkillsRaw(requestParameters: GetCharactersCharacterIdSkillsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharactersSkills>> {
        const requestOptions = await this.getCharactersCharacterIdSkillsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CharactersSkillsFromJSON(jsonValue));
    }

    /**
     * List all trained skills for the given character.  Skills returned by this route can be out-of-date if the character hasn\'t logged in since one or more skills completed training. Use the /skillqueue route to check for skills that completed training. Entries that are in the past need to be applied on top of this list to get an accurate view of the character\'s current skills.
     * Get character skills
     */
    async getCharactersCharacterIdSkills(requestParameters: GetCharactersCharacterIdSkillsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CharactersSkills> {
        const response = await this.getCharactersCharacterIdSkillsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const GetCharactersCharacterIdAttributesXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetCharactersCharacterIdAttributesXCompatibilityDateEnum = typeof GetCharactersCharacterIdAttributesXCompatibilityDateEnum[keyof typeof GetCharactersCharacterIdAttributesXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCharactersCharacterIdAttributesAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCharactersCharacterIdAttributesAcceptLanguageEnum = typeof GetCharactersCharacterIdAttributesAcceptLanguageEnum[keyof typeof GetCharactersCharacterIdAttributesAcceptLanguageEnum];
/**
 * @export
 */
export const GetCharactersCharacterIdSkillqueueXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetCharactersCharacterIdSkillqueueXCompatibilityDateEnum = typeof GetCharactersCharacterIdSkillqueueXCompatibilityDateEnum[keyof typeof GetCharactersCharacterIdSkillqueueXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCharactersCharacterIdSkillqueueAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCharactersCharacterIdSkillqueueAcceptLanguageEnum = typeof GetCharactersCharacterIdSkillqueueAcceptLanguageEnum[keyof typeof GetCharactersCharacterIdSkillqueueAcceptLanguageEnum];
/**
 * @export
 */
export const GetCharactersCharacterIdSkillsXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type GetCharactersCharacterIdSkillsXCompatibilityDateEnum = typeof GetCharactersCharacterIdSkillsXCompatibilityDateEnum[keyof typeof GetCharactersCharacterIdSkillsXCompatibilityDateEnum];
/**
 * @export
 */
export const GetCharactersCharacterIdSkillsAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type GetCharactersCharacterIdSkillsAcceptLanguageEnum = typeof GetCharactersCharacterIdSkillsAcceptLanguageEnum[keyof typeof GetCharactersCharacterIdSkillsAcceptLanguageEnum];
