/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type EsiError,
    EsiErrorFromJSON,
    EsiErrorToJSON,
} from '../models/EsiError';
import {
    type PostUiOpenwindowNewmailRequest,
    PostUiOpenwindowNewmailRequestFromJSON,
    PostUiOpenwindowNewmailRequestToJSON,
} from '../models/PostUiOpenwindowNewmailRequest';

export interface PostUiAutopilotWaypointRequest {
    addToBeginning: boolean;
    clearOtherWaypoints: boolean;
    destinationId: number;
    xCompatibilityDate: PostUiAutopilotWaypointXCompatibilityDateEnum;
    acceptLanguage?: PostUiAutopilotWaypointAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface PostUiOpenwindowContractRequest {
    contractId: number;
    xCompatibilityDate: PostUiOpenwindowContractXCompatibilityDateEnum;
    acceptLanguage?: PostUiOpenwindowContractAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface PostUiOpenwindowInformationRequest {
    targetId: number;
    xCompatibilityDate: PostUiOpenwindowInformationXCompatibilityDateEnum;
    acceptLanguage?: PostUiOpenwindowInformationAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface PostUiOpenwindowMarketdetailsRequest {
    typeId: number;
    xCompatibilityDate: PostUiOpenwindowMarketdetailsXCompatibilityDateEnum;
    acceptLanguage?: PostUiOpenwindowMarketdetailsAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

export interface PostUiOpenwindowNewmailOperationRequest {
    xCompatibilityDate: PostUiOpenwindowNewmailOperationXCompatibilityDateEnum;
    postUiOpenwindowNewmailRequest: PostUiOpenwindowNewmailRequest;
    acceptLanguage?: PostUiOpenwindowNewmailOperationAcceptLanguageEnum;
    ifNoneMatch?: string;
    xTenant?: string;
    ifModifiedSince?: string;
}

/**
 * 
 */
export class UserInterfaceApi extends runtime.BaseAPI {

    /**
     * Creates request options for postUiAutopilotWaypoint without sending the request
     */
    async postUiAutopilotWaypointRequestOpts(requestParameters: PostUiAutopilotWaypointRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['addToBeginning'] == null) {
            throw new runtime.RequiredError(
                'addToBeginning',
                'Required parameter "addToBeginning" was null or undefined when calling postUiAutopilotWaypoint().'
            );
        }

        if (requestParameters['clearOtherWaypoints'] == null) {
            throw new runtime.RequiredError(
                'clearOtherWaypoints',
                'Required parameter "clearOtherWaypoints" was null or undefined when calling postUiAutopilotWaypoint().'
            );
        }

        if (requestParameters['destinationId'] == null) {
            throw new runtime.RequiredError(
                'destinationId',
                'Required parameter "destinationId" was null or undefined when calling postUiAutopilotWaypoint().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling postUiAutopilotWaypoint().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['addToBeginning'] != null) {
            queryParameters['add_to_beginning'] = requestParameters['addToBeginning'];
        }

        if (requestParameters['clearOtherWaypoints'] != null) {
            queryParameters['clear_other_waypoints'] = requestParameters['clearOtherWaypoints'];
        }

        if (requestParameters['destinationId'] != null) {
            queryParameters['destination_id'] = requestParameters['destinationId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-ui.write_waypoint.v1"]);
        }


        let urlPath = `/ui/autopilot/waypoint`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Set a solar system as autopilot waypoint
     * Set Autopilot Waypoint
     */
    async postUiAutopilotWaypointRaw(requestParameters: PostUiAutopilotWaypointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.postUiAutopilotWaypointRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Set a solar system as autopilot waypoint
     * Set Autopilot Waypoint
     */
    async postUiAutopilotWaypoint(requestParameters: PostUiAutopilotWaypointRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postUiAutopilotWaypointRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for postUiOpenwindowContract without sending the request
     */
    async postUiOpenwindowContractRequestOpts(requestParameters: PostUiOpenwindowContractRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['contractId'] == null) {
            throw new runtime.RequiredError(
                'contractId',
                'Required parameter "contractId" was null or undefined when calling postUiOpenwindowContract().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling postUiOpenwindowContract().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['contractId'] != null) {
            queryParameters['contract_id'] = requestParameters['contractId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-ui.open_window.v1"]);
        }


        let urlPath = `/ui/openwindow/contract`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Open the contract window inside the client
     * Open Contract Window
     */
    async postUiOpenwindowContractRaw(requestParameters: PostUiOpenwindowContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.postUiOpenwindowContractRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Open the contract window inside the client
     * Open Contract Window
     */
    async postUiOpenwindowContract(requestParameters: PostUiOpenwindowContractRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postUiOpenwindowContractRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for postUiOpenwindowInformation without sending the request
     */
    async postUiOpenwindowInformationRequestOpts(requestParameters: PostUiOpenwindowInformationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['targetId'] == null) {
            throw new runtime.RequiredError(
                'targetId',
                'Required parameter "targetId" was null or undefined when calling postUiOpenwindowInformation().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling postUiOpenwindowInformation().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['targetId'] != null) {
            queryParameters['target_id'] = requestParameters['targetId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-ui.open_window.v1"]);
        }


        let urlPath = `/ui/openwindow/information`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Open the information window for a character, corporation or alliance inside the client
     * Open Information Window
     */
    async postUiOpenwindowInformationRaw(requestParameters: PostUiOpenwindowInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.postUiOpenwindowInformationRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Open the information window for a character, corporation or alliance inside the client
     * Open Information Window
     */
    async postUiOpenwindowInformation(requestParameters: PostUiOpenwindowInformationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postUiOpenwindowInformationRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for postUiOpenwindowMarketdetails without sending the request
     */
    async postUiOpenwindowMarketdetailsRequestOpts(requestParameters: PostUiOpenwindowMarketdetailsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['typeId'] == null) {
            throw new runtime.RequiredError(
                'typeId',
                'Required parameter "typeId" was null or undefined when calling postUiOpenwindowMarketdetails().'
            );
        }

        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling postUiOpenwindowMarketdetails().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['typeId'] != null) {
            queryParameters['type_id'] = requestParameters['typeId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-ui.open_window.v1"]);
        }


        let urlPath = `/ui/openwindow/marketdetails`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Open the market details window for a specific typeID inside the client
     * Open Market Details
     */
    async postUiOpenwindowMarketdetailsRaw(requestParameters: PostUiOpenwindowMarketdetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.postUiOpenwindowMarketdetailsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Open the market details window for a specific typeID inside the client
     * Open Market Details
     */
    async postUiOpenwindowMarketdetails(requestParameters: PostUiOpenwindowMarketdetailsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postUiOpenwindowMarketdetailsRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for postUiOpenwindowNewmail without sending the request
     */
    async postUiOpenwindowNewmailRequestOpts(requestParameters: PostUiOpenwindowNewmailOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['xCompatibilityDate'] == null) {
            throw new runtime.RequiredError(
                'xCompatibilityDate',
                'Required parameter "xCompatibilityDate" was null or undefined when calling postUiOpenwindowNewmail().'
            );
        }

        if (requestParameters['postUiOpenwindowNewmailRequest'] == null) {
            throw new runtime.RequiredError(
                'postUiOpenwindowNewmailRequest',
                'Required parameter "postUiOpenwindowNewmailRequest" was null or undefined when calling postUiOpenwindowNewmail().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['acceptLanguage'] != null) {
            headerParameters['Accept-Language'] = String(requestParameters['acceptLanguage']);
        }

        if (requestParameters['ifNoneMatch'] != null) {
            headerParameters['If-None-Match'] = String(requestParameters['ifNoneMatch']);
        }

        if (requestParameters['xCompatibilityDate'] != null) {
            headerParameters['X-Compatibility-Date'] = String(requestParameters['xCompatibilityDate']);
        }

        if (requestParameters['xTenant'] != null) {
            headerParameters['X-Tenant'] = String(requestParameters['xTenant']);
        }

        if (requestParameters['ifModifiedSince'] != null) {
            headerParameters['If-Modified-Since'] = String(requestParameters['ifModifiedSince']);
        }

        if (this.configuration && this.configuration.accessToken) {
            // oauth required
            headerParameters["Authorization"] = await this.configuration.accessToken("OAuth2", ["esi-ui.open_window.v1"]);
        }


        let urlPath = `/ui/openwindow/newmail`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostUiOpenwindowNewmailRequestToJSON(requestParameters['postUiOpenwindowNewmailRequest']),
        };
    }

    /**
     * Open the New Mail window, according to settings from the request if applicable
     * Open New Mail Window
     */
    async postUiOpenwindowNewmailRaw(requestParameters: PostUiOpenwindowNewmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.postUiOpenwindowNewmailRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Open the New Mail window, according to settings from the request if applicable
     * Open New Mail Window
     */
    async postUiOpenwindowNewmail(requestParameters: PostUiOpenwindowNewmailOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.postUiOpenwindowNewmailRaw(requestParameters, initOverrides);
    }

}

/**
 * @export
 */
export const PostUiAutopilotWaypointXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type PostUiAutopilotWaypointXCompatibilityDateEnum = typeof PostUiAutopilotWaypointXCompatibilityDateEnum[keyof typeof PostUiAutopilotWaypointXCompatibilityDateEnum];
/**
 * @export
 */
export const PostUiAutopilotWaypointAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type PostUiAutopilotWaypointAcceptLanguageEnum = typeof PostUiAutopilotWaypointAcceptLanguageEnum[keyof typeof PostUiAutopilotWaypointAcceptLanguageEnum];
/**
 * @export
 */
export const PostUiOpenwindowContractXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type PostUiOpenwindowContractXCompatibilityDateEnum = typeof PostUiOpenwindowContractXCompatibilityDateEnum[keyof typeof PostUiOpenwindowContractXCompatibilityDateEnum];
/**
 * @export
 */
export const PostUiOpenwindowContractAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type PostUiOpenwindowContractAcceptLanguageEnum = typeof PostUiOpenwindowContractAcceptLanguageEnum[keyof typeof PostUiOpenwindowContractAcceptLanguageEnum];
/**
 * @export
 */
export const PostUiOpenwindowInformationXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type PostUiOpenwindowInformationXCompatibilityDateEnum = typeof PostUiOpenwindowInformationXCompatibilityDateEnum[keyof typeof PostUiOpenwindowInformationXCompatibilityDateEnum];
/**
 * @export
 */
export const PostUiOpenwindowInformationAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type PostUiOpenwindowInformationAcceptLanguageEnum = typeof PostUiOpenwindowInformationAcceptLanguageEnum[keyof typeof PostUiOpenwindowInformationAcceptLanguageEnum];
/**
 * @export
 */
export const PostUiOpenwindowMarketdetailsXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type PostUiOpenwindowMarketdetailsXCompatibilityDateEnum = typeof PostUiOpenwindowMarketdetailsXCompatibilityDateEnum[keyof typeof PostUiOpenwindowMarketdetailsXCompatibilityDateEnum];
/**
 * @export
 */
export const PostUiOpenwindowMarketdetailsAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type PostUiOpenwindowMarketdetailsAcceptLanguageEnum = typeof PostUiOpenwindowMarketdetailsAcceptLanguageEnum[keyof typeof PostUiOpenwindowMarketdetailsAcceptLanguageEnum];
/**
 * @export
 */
export const PostUiOpenwindowNewmailOperationXCompatibilityDateEnum = {
    _20200101: '2020-01-01'
} as const;
export type PostUiOpenwindowNewmailOperationXCompatibilityDateEnum = typeof PostUiOpenwindowNewmailOperationXCompatibilityDateEnum[keyof typeof PostUiOpenwindowNewmailOperationXCompatibilityDateEnum];
/**
 * @export
 */
export const PostUiOpenwindowNewmailOperationAcceptLanguageEnum = {
    En: 'en',
    De: 'de',
    Fr: 'fr',
    Ja: 'ja',
    Ru: 'ru',
    Zh: 'zh',
    Ko: 'ko',
    Es: 'es'
} as const;
export type PostUiOpenwindowNewmailOperationAcceptLanguageEnum = typeof PostUiOpenwindowNewmailOperationAcceptLanguageEnum[keyof typeof PostUiOpenwindowNewmailOperationAcceptLanguageEnum];
