/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllianceDetail
 */
export interface AllianceDetail {
    /**
     * Alliance's creator corporation ID
     * @type {number}
     * @memberof AllianceDetail
     */
    creatorCorporationId: number;
    /**
     * Alliance's creator ID
     * @type {number}
     * @memberof AllianceDetail
     */
    creatorId: number;
    /**
     * Alliance's founding date
     * @type {Date}
     * @memberof AllianceDetail
     */
    dateFounded: Date;
    /**
     * Alliance's executor corporation ID
     * @type {number}
     * @memberof AllianceDetail
     */
    executorCorporationId?: number;
    /**
     * Alliance's faction ID
     * @type {number}
     * @memberof AllianceDetail
     */
    factionId?: number;
    /**
     * Alliance's name
     * @type {string}
     * @memberof AllianceDetail
     */
    name: string;
    /**
     * Alliance's ticker
     * @type {string}
     * @memberof AllianceDetail
     */
    ticker: string;
}

/**
 * Check if a given object implements the AllianceDetail interface.
 */
export function instanceOfAllianceDetail(value: object): value is AllianceDetail {
    if ((!('creatorCorporationId' in (value as Record<string, any>)) && !('creator_corporation_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['creatorCorporationId'] === undefined && (value as Record<string, any>)['creator_corporation_id'] === undefined)) return false;
    if ((!('creatorId' in (value as Record<string, any>)) && !('creator_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['creatorId'] === undefined && (value as Record<string, any>)['creator_id'] === undefined)) return false;
    if ((!('dateFounded' in (value as Record<string, any>)) && !('date_founded' in (value as Record<string, any>))) || ((value as Record<string, any>)['dateFounded'] === undefined && (value as Record<string, any>)['date_founded'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('ticker' in value) || value['ticker'] === undefined) return false;
    return true;
}

export function AllianceDetailFromJSON(json: any): AllianceDetail {
    return AllianceDetailFromJSONTyped(json, false);
}

export function AllianceDetailFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllianceDetail {
    if (json == null) {
        return json;
    }
    return {
        
        'creatorCorporationId': json['creator_corporation_id'],
        'creatorId': json['creator_id'],
        'dateFounded': (new Date(json['date_founded'])),
        'executorCorporationId': json['executor_corporation_id'] == null ? undefined : json['executor_corporation_id'],
        'factionId': json['faction_id'] == null ? undefined : json['faction_id'],
        'name': json['name'],
        'ticker': json['ticker'],
    };
}

export function AllianceDetailToJSON(json: any): AllianceDetail {
    return AllianceDetailToJSONTyped(json, false);
}

export function AllianceDetailToJSONTyped(value?: AllianceDetail | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'creator_corporation_id': value['creatorCorporationId'],
        'creator_id': value['creatorId'],
        'date_founded': value['dateFounded'].toISOString(),
        'executor_corporation_id': value['executorCorporationId'],
        'faction_id': value['factionId'],
        'name': value['name'],
        'ticker': value['ticker'],
    };
}

