/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersCharacterIdPlanetsGetInner
 */
export interface CharactersCharacterIdPlanetsGetInner {
    /**
     * 
     * @type {Date}
     * @memberof CharactersCharacterIdPlanetsGetInner
     */
    lastUpdate: Date;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdPlanetsGetInner
     */
    numPins: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdPlanetsGetInner
     */
    ownerId: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdPlanetsGetInner
     */
    planetId: number;
    /**
     * 
     * @type {CharactersCharacterIdPlanetsGetInnerPlanetTypeEnum}
     * @memberof CharactersCharacterIdPlanetsGetInner
     */
    planetType: CharactersCharacterIdPlanetsGetInnerPlanetTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdPlanetsGetInner
     */
    solarSystemId: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdPlanetsGetInner
     */
    upgradeLevel: number;
}


/**
 * @export
 */
export const CharactersCharacterIdPlanetsGetInnerPlanetTypeEnum = {
    Temperate: 'temperate',
    Barren: 'barren',
    Oceanic: 'oceanic',
    Ice: 'ice',
    Gas: 'gas',
    Lava: 'lava',
    Storm: 'storm',
    Plasma: 'plasma'
} as const;
export type CharactersCharacterIdPlanetsGetInnerPlanetTypeEnum = typeof CharactersCharacterIdPlanetsGetInnerPlanetTypeEnum[keyof typeof CharactersCharacterIdPlanetsGetInnerPlanetTypeEnum];


/**
 * Check if a given object implements the CharactersCharacterIdPlanetsGetInner interface.
 */
export function instanceOfCharactersCharacterIdPlanetsGetInner(value: object): value is CharactersCharacterIdPlanetsGetInner {
    if ((!('lastUpdate' in (value as Record<string, any>)) && !('last_update' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastUpdate'] === undefined && (value as Record<string, any>)['last_update'] === undefined)) return false;
    if ((!('numPins' in (value as Record<string, any>)) && !('num_pins' in (value as Record<string, any>))) || ((value as Record<string, any>)['numPins'] === undefined && (value as Record<string, any>)['num_pins'] === undefined)) return false;
    if ((!('ownerId' in (value as Record<string, any>)) && !('owner_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownerId'] === undefined && (value as Record<string, any>)['owner_id'] === undefined)) return false;
    if ((!('planetId' in (value as Record<string, any>)) && !('planet_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['planetId'] === undefined && (value as Record<string, any>)['planet_id'] === undefined)) return false;
    if ((!('planetType' in (value as Record<string, any>)) && !('planet_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['planetType'] === undefined && (value as Record<string, any>)['planet_type'] === undefined)) return false;
    if ((!('solarSystemId' in (value as Record<string, any>)) && !('solar_system_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['solarSystemId'] === undefined && (value as Record<string, any>)['solar_system_id'] === undefined)) return false;
    if ((!('upgradeLevel' in (value as Record<string, any>)) && !('upgrade_level' in (value as Record<string, any>))) || ((value as Record<string, any>)['upgradeLevel'] === undefined && (value as Record<string, any>)['upgrade_level'] === undefined)) return false;
    return true;
}

export function CharactersCharacterIdPlanetsGetInnerFromJSON(json: any): CharactersCharacterIdPlanetsGetInner {
    return CharactersCharacterIdPlanetsGetInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdPlanetsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdPlanetsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'lastUpdate': (new Date(json['last_update'])),
        'numPins': json['num_pins'],
        'ownerId': json['owner_id'],
        'planetId': json['planet_id'],
        'planetType': json['planet_type'],
        'solarSystemId': json['solar_system_id'],
        'upgradeLevel': json['upgrade_level'],
    };
}

export function CharactersCharacterIdPlanetsGetInnerToJSON(json: any): CharactersCharacterIdPlanetsGetInner {
    return CharactersCharacterIdPlanetsGetInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdPlanetsGetInnerToJSONTyped(value?: CharactersCharacterIdPlanetsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_update': value['lastUpdate'].toISOString(),
        'num_pins': value['numPins'],
        'owner_id': value['ownerId'],
        'planet_id': value['planetId'],
        'planet_type': value['planetType'],
        'solar_system_id': value['solarSystemId'],
        'upgrade_level': value['upgradeLevel'],
    };
}

