/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersCharacterIdNotificationsContactsGetInner
 */
export interface CharactersCharacterIdNotificationsContactsGetInner {
    /**
     * 
     * @type {string}
     * @memberof CharactersCharacterIdNotificationsContactsGetInner
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdNotificationsContactsGetInner
     */
    notificationId: number;
    /**
     * 
     * @type {Date}
     * @memberof CharactersCharacterIdNotificationsContactsGetInner
     */
    sendDate: Date;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdNotificationsContactsGetInner
     */
    senderCharacterId: number;
    /**
     * A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent
     * @type {number}
     * @memberof CharactersCharacterIdNotificationsContactsGetInner
     */
    standingLevel: number;
}

/**
 * Check if a given object implements the CharactersCharacterIdNotificationsContactsGetInner interface.
 */
export function instanceOfCharactersCharacterIdNotificationsContactsGetInner(value: object): value is CharactersCharacterIdNotificationsContactsGetInner {
    if (!('message' in value) || value['message'] === undefined) return false;
    if ((!('notificationId' in (value as Record<string, any>)) && !('notification_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['notificationId'] === undefined && (value as Record<string, any>)['notification_id'] === undefined)) return false;
    if ((!('sendDate' in (value as Record<string, any>)) && !('send_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['sendDate'] === undefined && (value as Record<string, any>)['send_date'] === undefined)) return false;
    if ((!('senderCharacterId' in (value as Record<string, any>)) && !('sender_character_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['senderCharacterId'] === undefined && (value as Record<string, any>)['sender_character_id'] === undefined)) return false;
    if ((!('standingLevel' in (value as Record<string, any>)) && !('standing_level' in (value as Record<string, any>))) || ((value as Record<string, any>)['standingLevel'] === undefined && (value as Record<string, any>)['standing_level'] === undefined)) return false;
    return true;
}

export function CharactersCharacterIdNotificationsContactsGetInnerFromJSON(json: any): CharactersCharacterIdNotificationsContactsGetInner {
    return CharactersCharacterIdNotificationsContactsGetInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdNotificationsContactsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdNotificationsContactsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'notificationId': json['notification_id'],
        'sendDate': (new Date(json['send_date'])),
        'senderCharacterId': json['sender_character_id'],
        'standingLevel': json['standing_level'],
    };
}

export function CharactersCharacterIdNotificationsContactsGetInnerToJSON(json: any): CharactersCharacterIdNotificationsContactsGetInner {
    return CharactersCharacterIdNotificationsContactsGetInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdNotificationsContactsGetInnerToJSONTyped(value?: CharactersCharacterIdNotificationsContactsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'notification_id': value['notificationId'],
        'send_date': value['sendDate'].toISOString(),
        'sender_character_id': value['senderCharacterId'],
        'standing_level': value['standingLevel'],
    };
}

