/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CharactersCharacterIdAssetsLocationsPostInnerPosition } from './CharactersCharacterIdAssetsLocationsPostInnerPosition';
import {
    CharactersCharacterIdAssetsLocationsPostInnerPositionFromJSON,
    CharactersCharacterIdAssetsLocationsPostInnerPositionFromJSONTyped,
    CharactersCharacterIdAssetsLocationsPostInnerPositionToJSON,
    CharactersCharacterIdAssetsLocationsPostInnerPositionToJSONTyped,
} from './CharactersCharacterIdAssetsLocationsPostInnerPosition';

/**
 * 
 * @export
 * @interface CharactersCharacterIdAssetsLocationsPostInner
 */
export interface CharactersCharacterIdAssetsLocationsPostInner {
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdAssetsLocationsPostInner
     */
    itemId: number;
    /**
     * 
     * @type {CharactersCharacterIdAssetsLocationsPostInnerPosition}
     * @memberof CharactersCharacterIdAssetsLocationsPostInner
     */
    position: CharactersCharacterIdAssetsLocationsPostInnerPosition;
}

/**
 * Check if a given object implements the CharactersCharacterIdAssetsLocationsPostInner interface.
 */
export function instanceOfCharactersCharacterIdAssetsLocationsPostInner(value: object): value is CharactersCharacterIdAssetsLocationsPostInner {
    if ((!('itemId' in (value as Record<string, any>)) && !('item_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['itemId'] === undefined && (value as Record<string, any>)['item_id'] === undefined)) return false;
    if (!('position' in value) || value['position'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdAssetsLocationsPostInnerFromJSON(json: any): CharactersCharacterIdAssetsLocationsPostInner {
    return CharactersCharacterIdAssetsLocationsPostInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdAssetsLocationsPostInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdAssetsLocationsPostInner {
    if (json == null) {
        return json;
    }
    return {
        
        'itemId': json['item_id'],
        'position': CharactersCharacterIdAssetsLocationsPostInnerPositionFromJSON(json['position']),
    };
}

export function CharactersCharacterIdAssetsLocationsPostInnerToJSON(json: any): CharactersCharacterIdAssetsLocationsPostInner {
    return CharactersCharacterIdAssetsLocationsPostInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdAssetsLocationsPostInnerToJSONTyped(value?: CharactersCharacterIdAssetsLocationsPostInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'item_id': value['itemId'],
        'position': CharactersCharacterIdAssetsLocationsPostInnerPositionToJSON(value['position']),
    };
}

