/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersCharacterIdContractsGetInner
 */
export interface CharactersCharacterIdContractsGetInner {
    /**
     * Who will accept the contract
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    acceptorId: number;
    /**
     * ID to whom the contract is assigned, can be alliance, corporation or character ID
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    assigneeId: number;
    /**
     * To whom the contract is available
     * @type {CharactersCharacterIdContractsGetInnerAvailabilityEnum}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    availability: CharactersCharacterIdContractsGetInnerAvailabilityEnum;
    /**
     * Buyout price (for Auctions only)
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    buyout?: number;
    /**
     * Collateral price (for Couriers only)
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    collateral?: number;
    /**
     * 
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    contractId: number;
    /**
     * Date of confirmation of contract
     * @type {Date}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    dateAccepted?: Date;
    /**
     * Date of completed of contract
     * @type {Date}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    dateCompleted?: Date;
    /**
     * Expiration date of the contract
     * @type {Date}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    dateExpired: Date;
    /**
     * Сreation date of the contract
     * @type {Date}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    dateIssued: Date;
    /**
     * Number of days to perform the contract
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    daysToComplete?: number;
    /**
     * End location ID (for Couriers contract)
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    endLocationId?: number;
    /**
     * true if the contract was issued on behalf of the issuer's corporation
     * @type {boolean}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    forCorporation: boolean;
    /**
     * Character's corporation ID for the issuer
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    issuerCorporationId: number;
    /**
     * Character ID for the issuer
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    issuerId: number;
    /**
     * Price of contract (for ItemsExchange and Auctions)
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    price?: number;
    /**
     * Remuneration for contract (for Couriers only)
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    reward?: number;
    /**
     * Start location ID (for Couriers contract)
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    startLocationId?: number;
    /**
     * Status of the the contract
     * @type {CharactersCharacterIdContractsGetInnerStatusEnum}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    status: CharactersCharacterIdContractsGetInnerStatusEnum;
    /**
     * Title of the contract
     * @type {string}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    title?: string;
    /**
     * Type of the contract
     * @type {CharactersCharacterIdContractsGetInnerTypeEnum}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    type: CharactersCharacterIdContractsGetInnerTypeEnum;
    /**
     * Volume of items in the contract
     * @type {number}
     * @memberof CharactersCharacterIdContractsGetInner
     */
    volume?: number;
}


/**
 * @export
 */
export const CharactersCharacterIdContractsGetInnerAvailabilityEnum = {
    Public: 'public',
    Personal: 'personal',
    Corporation: 'corporation',
    Alliance: 'alliance'
} as const;
export type CharactersCharacterIdContractsGetInnerAvailabilityEnum = typeof CharactersCharacterIdContractsGetInnerAvailabilityEnum[keyof typeof CharactersCharacterIdContractsGetInnerAvailabilityEnum];

/**
 * @export
 */
export const CharactersCharacterIdContractsGetInnerStatusEnum = {
    Outstanding: 'outstanding',
    InProgress: 'in_progress',
    FinishedIssuer: 'finished_issuer',
    FinishedContractor: 'finished_contractor',
    Finished: 'finished',
    Cancelled: 'cancelled',
    Rejected: 'rejected',
    Failed: 'failed',
    Deleted: 'deleted',
    Reversed: 'reversed'
} as const;
export type CharactersCharacterIdContractsGetInnerStatusEnum = typeof CharactersCharacterIdContractsGetInnerStatusEnum[keyof typeof CharactersCharacterIdContractsGetInnerStatusEnum];

/**
 * @export
 */
export const CharactersCharacterIdContractsGetInnerTypeEnum = {
    Unknown: 'unknown',
    ItemExchange: 'item_exchange',
    Auction: 'auction',
    Courier: 'courier',
    Loan: 'loan'
} as const;
export type CharactersCharacterIdContractsGetInnerTypeEnum = typeof CharactersCharacterIdContractsGetInnerTypeEnum[keyof typeof CharactersCharacterIdContractsGetInnerTypeEnum];


/**
 * Check if a given object implements the CharactersCharacterIdContractsGetInner interface.
 */
export function instanceOfCharactersCharacterIdContractsGetInner(value: object): value is CharactersCharacterIdContractsGetInner {
    if ((!('acceptorId' in (value as Record<string, any>)) && !('acceptor_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['acceptorId'] === undefined && (value as Record<string, any>)['acceptor_id'] === undefined)) return false;
    if ((!('assigneeId' in (value as Record<string, any>)) && !('assignee_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['assigneeId'] === undefined && (value as Record<string, any>)['assignee_id'] === undefined)) return false;
    if (!('availability' in value) || value['availability'] === undefined) return false;
    if ((!('contractId' in (value as Record<string, any>)) && !('contract_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['contractId'] === undefined && (value as Record<string, any>)['contract_id'] === undefined)) return false;
    if ((!('dateExpired' in (value as Record<string, any>)) && !('date_expired' in (value as Record<string, any>))) || ((value as Record<string, any>)['dateExpired'] === undefined && (value as Record<string, any>)['date_expired'] === undefined)) return false;
    if ((!('dateIssued' in (value as Record<string, any>)) && !('date_issued' in (value as Record<string, any>))) || ((value as Record<string, any>)['dateIssued'] === undefined && (value as Record<string, any>)['date_issued'] === undefined)) return false;
    if ((!('forCorporation' in (value as Record<string, any>)) && !('for_corporation' in (value as Record<string, any>))) || ((value as Record<string, any>)['forCorporation'] === undefined && (value as Record<string, any>)['for_corporation'] === undefined)) return false;
    if ((!('issuerCorporationId' in (value as Record<string, any>)) && !('issuer_corporation_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['issuerCorporationId'] === undefined && (value as Record<string, any>)['issuer_corporation_id'] === undefined)) return false;
    if ((!('issuerId' in (value as Record<string, any>)) && !('issuer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['issuerId'] === undefined && (value as Record<string, any>)['issuer_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function CharactersCharacterIdContractsGetInnerFromJSON(json: any): CharactersCharacterIdContractsGetInner {
    return CharactersCharacterIdContractsGetInnerFromJSONTyped(json, false);
}

export function CharactersCharacterIdContractsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersCharacterIdContractsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'acceptorId': json['acceptor_id'],
        'assigneeId': json['assignee_id'],
        'availability': json['availability'],
        'buyout': json['buyout'] == null ? undefined : json['buyout'],
        'collateral': json['collateral'] == null ? undefined : json['collateral'],
        'contractId': json['contract_id'],
        'dateAccepted': json['date_accepted'] == null ? undefined : (new Date(json['date_accepted'])),
        'dateCompleted': json['date_completed'] == null ? undefined : (new Date(json['date_completed'])),
        'dateExpired': (new Date(json['date_expired'])),
        'dateIssued': (new Date(json['date_issued'])),
        'daysToComplete': json['days_to_complete'] == null ? undefined : json['days_to_complete'],
        'endLocationId': json['end_location_id'] == null ? undefined : json['end_location_id'],
        'forCorporation': json['for_corporation'],
        'issuerCorporationId': json['issuer_corporation_id'],
        'issuerId': json['issuer_id'],
        'price': json['price'] == null ? undefined : json['price'],
        'reward': json['reward'] == null ? undefined : json['reward'],
        'startLocationId': json['start_location_id'] == null ? undefined : json['start_location_id'],
        'status': json['status'],
        'title': json['title'] == null ? undefined : json['title'],
        'type': json['type'],
        'volume': json['volume'] == null ? undefined : json['volume'],
    };
}

export function CharactersCharacterIdContractsGetInnerToJSON(json: any): CharactersCharacterIdContractsGetInner {
    return CharactersCharacterIdContractsGetInnerToJSONTyped(json, false);
}

export function CharactersCharacterIdContractsGetInnerToJSONTyped(value?: CharactersCharacterIdContractsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acceptor_id': value['acceptorId'],
        'assignee_id': value['assigneeId'],
        'availability': value['availability'],
        'buyout': value['buyout'],
        'collateral': value['collateral'],
        'contract_id': value['contractId'],
        'date_accepted': value['dateAccepted'] == null ? value['dateAccepted'] : value['dateAccepted'].toISOString(),
        'date_completed': value['dateCompleted'] == null ? value['dateCompleted'] : value['dateCompleted'].toISOString(),
        'date_expired': value['dateExpired'].toISOString(),
        'date_issued': value['dateIssued'].toISOString(),
        'days_to_complete': value['daysToComplete'],
        'end_location_id': value['endLocationId'],
        'for_corporation': value['forCorporation'],
        'issuer_corporation_id': value['issuerCorporationId'],
        'issuer_id': value['issuerId'],
        'price': value['price'],
        'reward': value['reward'],
        'start_location_id': value['startLocationId'],
        'status': value['status'],
        'title': value['title'],
        'type': value['type'],
        'volume': value['volume'],
    };
}

