/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractsPublicBidsContractIdGetInner
 */
export interface ContractsPublicBidsContractIdGetInner {
    /**
     * The amount bid, in ISK
     * @type {number}
     * @memberof ContractsPublicBidsContractIdGetInner
     */
    amount: number;
    /**
     * Unique ID for the bid
     * @type {number}
     * @memberof ContractsPublicBidsContractIdGetInner
     */
    bidId: number;
    /**
     * Datetime when the bid was placed
     * @type {Date}
     * @memberof ContractsPublicBidsContractIdGetInner
     */
    dateBid: Date;
}

/**
 * Check if a given object implements the ContractsPublicBidsContractIdGetInner interface.
 */
export function instanceOfContractsPublicBidsContractIdGetInner(value: object): value is ContractsPublicBidsContractIdGetInner {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if ((!('bidId' in (value as Record<string, any>)) && !('bid_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['bidId'] === undefined && (value as Record<string, any>)['bid_id'] === undefined)) return false;
    if ((!('dateBid' in (value as Record<string, any>)) && !('date_bid' in (value as Record<string, any>))) || ((value as Record<string, any>)['dateBid'] === undefined && (value as Record<string, any>)['date_bid'] === undefined)) return false;
    return true;
}

export function ContractsPublicBidsContractIdGetInnerFromJSON(json: any): ContractsPublicBidsContractIdGetInner {
    return ContractsPublicBidsContractIdGetInnerFromJSONTyped(json, false);
}

export function ContractsPublicBidsContractIdGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractsPublicBidsContractIdGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'bidId': json['bid_id'],
        'dateBid': (new Date(json['date_bid'])),
    };
}

export function ContractsPublicBidsContractIdGetInnerToJSON(json: any): ContractsPublicBidsContractIdGetInner {
    return ContractsPublicBidsContractIdGetInnerToJSONTyped(json, false);
}

export function ContractsPublicBidsContractIdGetInnerToJSONTyped(value?: ContractsPublicBidsContractIdGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'bid_id': value['bidId'],
        'date_bid': value['dateBid'].toISOString(),
    };
}

