/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorporationsCorporationIdRolesHistoryGetInner
 */
export interface CorporationsCorporationIdRolesHistoryGetInner {
    /**
     * 
     * @type {Date}
     * @memberof CorporationsCorporationIdRolesHistoryGetInner
     */
    changedAt: Date;
    /**
     * The character whose roles are changed
     * @type {number}
     * @memberof CorporationsCorporationIdRolesHistoryGetInner
     */
    characterId: number;
    /**
     * ID of the character who issued this change
     * @type {number}
     * @memberof CorporationsCorporationIdRolesHistoryGetInner
     */
    issuerId: number;
    /**
     * 
     * @type {Set<CorporationsCorporationIdRolesHistoryGetInnerNewRolesEnum>}
     * @memberof CorporationsCorporationIdRolesHistoryGetInner
     */
    newRoles: Set<CorporationsCorporationIdRolesHistoryGetInnerNewRolesEnum>;
    /**
     * 
     * @type {Set<CorporationsCorporationIdRolesHistoryGetInnerOldRolesEnum>}
     * @memberof CorporationsCorporationIdRolesHistoryGetInner
     */
    oldRoles: Set<CorporationsCorporationIdRolesHistoryGetInnerOldRolesEnum>;
    /**
     * 
     * @type {CorporationsCorporationIdRolesHistoryGetInnerRoleTypeEnum}
     * @memberof CorporationsCorporationIdRolesHistoryGetInner
     */
    roleType: CorporationsCorporationIdRolesHistoryGetInnerRoleTypeEnum;
}


/**
 * @export
 */
export const CorporationsCorporationIdRolesHistoryGetInnerNewRolesEnum = {
    AccountTake1: 'Account_Take_1',
    AccountTake2: 'Account_Take_2',
    AccountTake3: 'Account_Take_3',
    AccountTake4: 'Account_Take_4',
    AccountTake5: 'Account_Take_5',
    AccountTake6: 'Account_Take_6',
    AccountTake7: 'Account_Take_7',
    Accountant: 'Accountant',
    Auditor: 'Auditor',
    BrandManager: 'Brand_Manager',
    CommunicationsOfficer: 'Communications_Officer',
    ConfigEquipment: 'Config_Equipment',
    ConfigStarbaseEquipment: 'Config_Starbase_Equipment',
    ContainerTake1: 'Container_Take_1',
    ContainerTake2: 'Container_Take_2',
    ContainerTake3: 'Container_Take_3',
    ContainerTake4: 'Container_Take_4',
    ContainerTake5: 'Container_Take_5',
    ContainerTake6: 'Container_Take_6',
    ContainerTake7: 'Container_Take_7',
    ContractManager: 'Contract_Manager',
    DeliveriesContainerTake: 'Deliveries_Container_Take',
    DeliveriesQuery: 'Deliveries_Query',
    DeliveriesTake: 'Deliveries_Take',
    Diplomat: 'Diplomat',
    Director: 'Director',
    FactoryManager: 'Factory_Manager',
    FittingManager: 'Fitting_Manager',
    HangarQuery1: 'Hangar_Query_1',
    HangarQuery2: 'Hangar_Query_2',
    HangarQuery3: 'Hangar_Query_3',
    HangarQuery4: 'Hangar_Query_4',
    HangarQuery5: 'Hangar_Query_5',
    HangarQuery6: 'Hangar_Query_6',
    HangarQuery7: 'Hangar_Query_7',
    HangarTake1: 'Hangar_Take_1',
    HangarTake2: 'Hangar_Take_2',
    HangarTake3: 'Hangar_Take_3',
    HangarTake4: 'Hangar_Take_4',
    HangarTake5: 'Hangar_Take_5',
    HangarTake6: 'Hangar_Take_6',
    HangarTake7: 'Hangar_Take_7',
    JuniorAccountant: 'Junior_Accountant',
    PersonnelManager: 'Personnel_Manager',
    ProjectManager: 'Project_Manager',
    RentFactoryFacility: 'Rent_Factory_Facility',
    RentOffice: 'Rent_Office',
    RentResearchFacility: 'Rent_Research_Facility',
    SecurityOfficer: 'Security_Officer',
    SkillPlanManager: 'Skill_Plan_Manager',
    StarbaseDefenseOperator: 'Starbase_Defense_Operator',
    StarbaseFuelTechnician: 'Starbase_Fuel_Technician',
    StationManager: 'Station_Manager',
    Trader: 'Trader'
} as const;
export type CorporationsCorporationIdRolesHistoryGetInnerNewRolesEnum = typeof CorporationsCorporationIdRolesHistoryGetInnerNewRolesEnum[keyof typeof CorporationsCorporationIdRolesHistoryGetInnerNewRolesEnum];

/**
 * @export
 */
export const CorporationsCorporationIdRolesHistoryGetInnerOldRolesEnum = {
    AccountTake1: 'Account_Take_1',
    AccountTake2: 'Account_Take_2',
    AccountTake3: 'Account_Take_3',
    AccountTake4: 'Account_Take_4',
    AccountTake5: 'Account_Take_5',
    AccountTake6: 'Account_Take_6',
    AccountTake7: 'Account_Take_7',
    Accountant: 'Accountant',
    Auditor: 'Auditor',
    BrandManager: 'Brand_Manager',
    CommunicationsOfficer: 'Communications_Officer',
    ConfigEquipment: 'Config_Equipment',
    ConfigStarbaseEquipment: 'Config_Starbase_Equipment',
    ContainerTake1: 'Container_Take_1',
    ContainerTake2: 'Container_Take_2',
    ContainerTake3: 'Container_Take_3',
    ContainerTake4: 'Container_Take_4',
    ContainerTake5: 'Container_Take_5',
    ContainerTake6: 'Container_Take_6',
    ContainerTake7: 'Container_Take_7',
    ContractManager: 'Contract_Manager',
    DeliveriesContainerTake: 'Deliveries_Container_Take',
    DeliveriesQuery: 'Deliveries_Query',
    DeliveriesTake: 'Deliveries_Take',
    Diplomat: 'Diplomat',
    Director: 'Director',
    FactoryManager: 'Factory_Manager',
    FittingManager: 'Fitting_Manager',
    HangarQuery1: 'Hangar_Query_1',
    HangarQuery2: 'Hangar_Query_2',
    HangarQuery3: 'Hangar_Query_3',
    HangarQuery4: 'Hangar_Query_4',
    HangarQuery5: 'Hangar_Query_5',
    HangarQuery6: 'Hangar_Query_6',
    HangarQuery7: 'Hangar_Query_7',
    HangarTake1: 'Hangar_Take_1',
    HangarTake2: 'Hangar_Take_2',
    HangarTake3: 'Hangar_Take_3',
    HangarTake4: 'Hangar_Take_4',
    HangarTake5: 'Hangar_Take_5',
    HangarTake6: 'Hangar_Take_6',
    HangarTake7: 'Hangar_Take_7',
    JuniorAccountant: 'Junior_Accountant',
    PersonnelManager: 'Personnel_Manager',
    ProjectManager: 'Project_Manager',
    RentFactoryFacility: 'Rent_Factory_Facility',
    RentOffice: 'Rent_Office',
    RentResearchFacility: 'Rent_Research_Facility',
    SecurityOfficer: 'Security_Officer',
    SkillPlanManager: 'Skill_Plan_Manager',
    StarbaseDefenseOperator: 'Starbase_Defense_Operator',
    StarbaseFuelTechnician: 'Starbase_Fuel_Technician',
    StationManager: 'Station_Manager',
    Trader: 'Trader'
} as const;
export type CorporationsCorporationIdRolesHistoryGetInnerOldRolesEnum = typeof CorporationsCorporationIdRolesHistoryGetInnerOldRolesEnum[keyof typeof CorporationsCorporationIdRolesHistoryGetInnerOldRolesEnum];

/**
 * @export
 */
export const CorporationsCorporationIdRolesHistoryGetInnerRoleTypeEnum = {
    GrantableRoles: 'grantable_roles',
    GrantableRolesAtBase: 'grantable_roles_at_base',
    GrantableRolesAtHq: 'grantable_roles_at_hq',
    GrantableRolesAtOther: 'grantable_roles_at_other',
    Roles: 'roles',
    RolesAtBase: 'roles_at_base',
    RolesAtHq: 'roles_at_hq',
    RolesAtOther: 'roles_at_other'
} as const;
export type CorporationsCorporationIdRolesHistoryGetInnerRoleTypeEnum = typeof CorporationsCorporationIdRolesHistoryGetInnerRoleTypeEnum[keyof typeof CorporationsCorporationIdRolesHistoryGetInnerRoleTypeEnum];


/**
 * Check if a given object implements the CorporationsCorporationIdRolesHistoryGetInner interface.
 */
export function instanceOfCorporationsCorporationIdRolesHistoryGetInner(value: object): value is CorporationsCorporationIdRolesHistoryGetInner {
    if ((!('changedAt' in (value as Record<string, any>)) && !('changed_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['changedAt'] === undefined && (value as Record<string, any>)['changed_at'] === undefined)) return false;
    if ((!('characterId' in (value as Record<string, any>)) && !('character_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['characterId'] === undefined && (value as Record<string, any>)['character_id'] === undefined)) return false;
    if ((!('issuerId' in (value as Record<string, any>)) && !('issuer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['issuerId'] === undefined && (value as Record<string, any>)['issuer_id'] === undefined)) return false;
    if ((!('newRoles' in (value as Record<string, any>)) && !('new_roles' in (value as Record<string, any>))) || ((value as Record<string, any>)['newRoles'] === undefined && (value as Record<string, any>)['new_roles'] === undefined)) return false;
    if ((!('oldRoles' in (value as Record<string, any>)) && !('old_roles' in (value as Record<string, any>))) || ((value as Record<string, any>)['oldRoles'] === undefined && (value as Record<string, any>)['old_roles'] === undefined)) return false;
    if ((!('roleType' in (value as Record<string, any>)) && !('role_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['roleType'] === undefined && (value as Record<string, any>)['role_type'] === undefined)) return false;
    return true;
}

export function CorporationsCorporationIdRolesHistoryGetInnerFromJSON(json: any): CorporationsCorporationIdRolesHistoryGetInner {
    return CorporationsCorporationIdRolesHistoryGetInnerFromJSONTyped(json, false);
}

export function CorporationsCorporationIdRolesHistoryGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationsCorporationIdRolesHistoryGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'changedAt': (new Date(json['changed_at'])),
        'characterId': json['character_id'],
        'issuerId': json['issuer_id'],
        'newRoles': new Set(json['new_roles']),
        'oldRoles': new Set(json['old_roles']),
        'roleType': json['role_type'],
    };
}

export function CorporationsCorporationIdRolesHistoryGetInnerToJSON(json: any): CorporationsCorporationIdRolesHistoryGetInner {
    return CorporationsCorporationIdRolesHistoryGetInnerToJSONTyped(json, false);
}

export function CorporationsCorporationIdRolesHistoryGetInnerToJSONTyped(value?: CorporationsCorporationIdRolesHistoryGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'changed_at': value['changedAt'].toISOString(),
        'character_id': value['characterId'],
        'issuer_id': value['issuerId'],
        'new_roles': Array.from(value['newRoles'] as Set<any>),
        'old_roles': Array.from(value['oldRoles'] as Set<any>),
        'role_type': value['roleType'],
    };
}

