/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorporationsCorporationIdAlliancehistoryGetInner
 */
export interface CorporationsCorporationIdAlliancehistoryGetInner {
    /**
     * 
     * @type {number}
     * @memberof CorporationsCorporationIdAlliancehistoryGetInner
     */
    allianceId?: number;
    /**
     * True if the alliance has been closed
     * @type {boolean}
     * @memberof CorporationsCorporationIdAlliancehistoryGetInner
     */
    isDeleted?: boolean;
    /**
     * An incrementing ID that can be used to canonically establish order of records in cases where dates may be ambiguous
     * @type {number}
     * @memberof CorporationsCorporationIdAlliancehistoryGetInner
     */
    recordId: number;
    /**
     * 
     * @type {Date}
     * @memberof CorporationsCorporationIdAlliancehistoryGetInner
     */
    startDate: Date;
}

/**
 * Check if a given object implements the CorporationsCorporationIdAlliancehistoryGetInner interface.
 */
export function instanceOfCorporationsCorporationIdAlliancehistoryGetInner(value: object): value is CorporationsCorporationIdAlliancehistoryGetInner {
    if ((!('recordId' in (value as Record<string, any>)) && !('record_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['recordId'] === undefined && (value as Record<string, any>)['record_id'] === undefined)) return false;
    if ((!('startDate' in (value as Record<string, any>)) && !('start_date' in (value as Record<string, any>))) || ((value as Record<string, any>)['startDate'] === undefined && (value as Record<string, any>)['start_date'] === undefined)) return false;
    return true;
}

export function CorporationsCorporationIdAlliancehistoryGetInnerFromJSON(json: any): CorporationsCorporationIdAlliancehistoryGetInner {
    return CorporationsCorporationIdAlliancehistoryGetInnerFromJSONTyped(json, false);
}

export function CorporationsCorporationIdAlliancehistoryGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationsCorporationIdAlliancehistoryGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'allianceId': json['alliance_id'] == null ? undefined : json['alliance_id'],
        'isDeleted': json['is_deleted'] == null ? undefined : json['is_deleted'],
        'recordId': json['record_id'],
        'startDate': (new Date(json['start_date'])),
    };
}

export function CorporationsCorporationIdAlliancehistoryGetInnerToJSON(json: any): CorporationsCorporationIdAlliancehistoryGetInner {
    return CorporationsCorporationIdAlliancehistoryGetInnerToJSONTyped(json, false);
}

export function CorporationsCorporationIdAlliancehistoryGetInnerToJSONTyped(value?: CorporationsCorporationIdAlliancehistoryGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alliance_id': value['allianceId'],
        'is_deleted': value['isDeleted'],
        'record_id': value['recordId'],
        'start_date': value['startDate'].toISOString(),
    };
}

