/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CorporationCorporationIdMiningObserversObserverIdGetInner
 */
export interface CorporationCorporationIdMiningObserversObserverIdGetInner {
    /**
     * The character that did the mining
     * 
     * @type {number}
     * @memberof CorporationCorporationIdMiningObserversObserverIdGetInner
     */
    characterId: number;
    /**
     * 
     * @type {Date}
     * @memberof CorporationCorporationIdMiningObserversObserverIdGetInner
     */
    lastUpdated: Date;
    /**
     * 
     * @type {number}
     * @memberof CorporationCorporationIdMiningObserversObserverIdGetInner
     */
    quantity: number;
    /**
     * The corporation id of the character at the time data was recorded.
     * 
     * @type {number}
     * @memberof CorporationCorporationIdMiningObserversObserverIdGetInner
     */
    recordedCorporationId: number;
    /**
     * 
     * @type {number}
     * @memberof CorporationCorporationIdMiningObserversObserverIdGetInner
     */
    typeId: number;
}

/**
 * Check if a given object implements the CorporationCorporationIdMiningObserversObserverIdGetInner interface.
 */
export function instanceOfCorporationCorporationIdMiningObserversObserverIdGetInner(value: object): value is CorporationCorporationIdMiningObserversObserverIdGetInner {
    if ((!('characterId' in (value as Record<string, any>)) && !('character_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['characterId'] === undefined && (value as Record<string, any>)['character_id'] === undefined)) return false;
    if ((!('lastUpdated' in (value as Record<string, any>)) && !('last_updated' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastUpdated'] === undefined && (value as Record<string, any>)['last_updated'] === undefined)) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if ((!('recordedCorporationId' in (value as Record<string, any>)) && !('recorded_corporation_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['recordedCorporationId'] === undefined && (value as Record<string, any>)['recorded_corporation_id'] === undefined)) return false;
    if ((!('typeId' in (value as Record<string, any>)) && !('type_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['typeId'] === undefined && (value as Record<string, any>)['type_id'] === undefined)) return false;
    return true;
}

export function CorporationCorporationIdMiningObserversObserverIdGetInnerFromJSON(json: any): CorporationCorporationIdMiningObserversObserverIdGetInner {
    return CorporationCorporationIdMiningObserversObserverIdGetInnerFromJSONTyped(json, false);
}

export function CorporationCorporationIdMiningObserversObserverIdGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationCorporationIdMiningObserversObserverIdGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'characterId': json['character_id'],
        'lastUpdated': (new Date(json['last_updated'])),
        'quantity': json['quantity'],
        'recordedCorporationId': json['recorded_corporation_id'],
        'typeId': json['type_id'],
    };
}

export function CorporationCorporationIdMiningObserversObserverIdGetInnerToJSON(json: any): CorporationCorporationIdMiningObserversObserverIdGetInner {
    return CorporationCorporationIdMiningObserversObserverIdGetInnerToJSONTyped(json, false);
}

export function CorporationCorporationIdMiningObserversObserverIdGetInnerToJSONTyped(value?: CorporationCorporationIdMiningObserversObserverIdGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'character_id': value['characterId'],
        'last_updated': value['lastUpdated'].toISOString().substring(0,10),
        'quantity': value['quantity'],
        'recorded_corporation_id': value['recordedCorporationId'],
        'type_id': value['typeId'],
    };
}

