/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Summary of kills done by the given corporation against enemy factions
 * @export
 * @interface CorporationsCorporationIdFwStatsGetKills
 */
export interface CorporationsCorporationIdFwStatsGetKills {
    /**
     * Last week's total number of kills by members of the given corporation against enemy factions
     * @type {number}
     * @memberof CorporationsCorporationIdFwStatsGetKills
     */
    lastWeek: number;
    /**
     * Total number of kills by members of the given corporation against enemy factions since the corporation enlisted
     * @type {number}
     * @memberof CorporationsCorporationIdFwStatsGetKills
     */
    total: number;
    /**
     * Yesterday's total number of kills by members of the given corporation against enemy factions
     * @type {number}
     * @memberof CorporationsCorporationIdFwStatsGetKills
     */
    yesterday: number;
}

/**
 * Check if a given object implements the CorporationsCorporationIdFwStatsGetKills interface.
 */
export function instanceOfCorporationsCorporationIdFwStatsGetKills(value: object): value is CorporationsCorporationIdFwStatsGetKills {
    if ((!('lastWeek' in (value as Record<string, any>)) && !('last_week' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastWeek'] === undefined && (value as Record<string, any>)['last_week'] === undefined)) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('yesterday' in value) || value['yesterday'] === undefined) return false;
    return true;
}

export function CorporationsCorporationIdFwStatsGetKillsFromJSON(json: any): CorporationsCorporationIdFwStatsGetKills {
    return CorporationsCorporationIdFwStatsGetKillsFromJSONTyped(json, false);
}

export function CorporationsCorporationIdFwStatsGetKillsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CorporationsCorporationIdFwStatsGetKills {
    if (json == null) {
        return json;
    }
    return {
        
        'lastWeek': json['last_week'],
        'total': json['total'],
        'yesterday': json['yesterday'],
    };
}

export function CorporationsCorporationIdFwStatsGetKillsToJSON(json: any): CorporationsCorporationIdFwStatsGetKills {
    return CorporationsCorporationIdFwStatsGetKillsToJSONTyped(json, false);
}

export function CorporationsCorporationIdFwStatsGetKillsToJSONTyped(value?: CorporationsCorporationIdFwStatsGetKills | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'last_week': value['lastWeek'],
        'total': value['total'],
        'yesterday': value['yesterday'],
    };
}

