/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorDetail } from './ErrorDetail';
import {
    ErrorDetailFromJSON,
    ErrorDetailFromJSONTyped,
    ErrorDetailToJSON,
    ErrorDetailToJSONTyped,
} from './ErrorDetail';

/**
 * 
 * @export
 * @interface EsiError
 */
export interface EsiError {
    /**
     * List of individual issues.
     * @type {Array<ErrorDetail>}
     * @memberof EsiError
     */
    details?: Array<ErrorDetail>;
    /**
     * Error message.
     * @type {string}
     * @memberof EsiError
     */
    error: string;
    /**
     * HTTP status code.
     * @type {number}
     * @memberof EsiError
     */
    status?: number;
}

/**
 * Check if a given object implements the EsiError interface.
 */
export function instanceOfEsiError(value: object): value is EsiError {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function EsiErrorFromJSON(json: any): EsiError {
    return EsiErrorFromJSONTyped(json, false);
}

export function EsiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EsiError {
    if (json == null) {
        return json;
    }
    return {
        
        'details': json['details'] == null ? undefined : ((json['details'] as Array<any>).map(ErrorDetailFromJSON)),
        'error': json['error'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function EsiErrorToJSON(json: any): EsiError {
    return EsiErrorToJSONTyped(json, false);
}

export function EsiErrorToJSONTyped(value?: EsiError | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'details': value['details'] == null ? undefined : ((value['details'] as Array<any>).map(ErrorDetailToJSON)),
        'error': value['error'],
        'status': value['status'],
    };
}

