/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 201 created object
 * @export
 * @interface FleetsFleetIdWingsWingIdSquadsPost
 */
export interface FleetsFleetIdWingsWingIdSquadsPost {
    /**
     * The squad_id of the newly created squad
     * @type {number}
     * @memberof FleetsFleetIdWingsWingIdSquadsPost
     */
    squadId: number;
}

/**
 * Check if a given object implements the FleetsFleetIdWingsWingIdSquadsPost interface.
 */
export function instanceOfFleetsFleetIdWingsWingIdSquadsPost(value: object): value is FleetsFleetIdWingsWingIdSquadsPost {
    if ((!('squadId' in (value as Record<string, any>)) && !('squad_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['squadId'] === undefined && (value as Record<string, any>)['squad_id'] === undefined)) return false;
    return true;
}

export function FleetsFleetIdWingsWingIdSquadsPostFromJSON(json: any): FleetsFleetIdWingsWingIdSquadsPost {
    return FleetsFleetIdWingsWingIdSquadsPostFromJSONTyped(json, false);
}

export function FleetsFleetIdWingsWingIdSquadsPostFromJSONTyped(json: any, ignoreDiscriminator: boolean): FleetsFleetIdWingsWingIdSquadsPost {
    if (json == null) {
        return json;
    }
    return {
        
        'squadId': json['squad_id'],
    };
}

export function FleetsFleetIdWingsWingIdSquadsPostToJSON(json: any): FleetsFleetIdWingsWingIdSquadsPost {
    return FleetsFleetIdWingsWingIdSquadsPostToJSONTyped(json, false);
}

export function FleetsFleetIdWingsWingIdSquadsPostToJSONTyped(value?: FleetsFleetIdWingsWingIdSquadsPost | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'squad_id': value['squadId'],
    };
}

