/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * yesterday object
 * @export
 * @interface FwLeaderboardsGetVictoryPointsYesterdayInner
 */
export interface FwLeaderboardsGetVictoryPointsYesterdayInner {
    /**
     * Amount of victory points
     * @type {number}
     * @memberof FwLeaderboardsGetVictoryPointsYesterdayInner
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof FwLeaderboardsGetVictoryPointsYesterdayInner
     */
    factionId?: number;
}

/**
 * Check if a given object implements the FwLeaderboardsGetVictoryPointsYesterdayInner interface.
 */
export function instanceOfFwLeaderboardsGetVictoryPointsYesterdayInner(value: object): value is FwLeaderboardsGetVictoryPointsYesterdayInner {
    return true;
}

export function FwLeaderboardsGetVictoryPointsYesterdayInnerFromJSON(json: any): FwLeaderboardsGetVictoryPointsYesterdayInner {
    return FwLeaderboardsGetVictoryPointsYesterdayInnerFromJSONTyped(json, false);
}

export function FwLeaderboardsGetVictoryPointsYesterdayInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FwLeaderboardsGetVictoryPointsYesterdayInner {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'factionId': json['faction_id'] == null ? undefined : json['faction_id'],
    };
}

export function FwLeaderboardsGetVictoryPointsYesterdayInnerToJSON(json: any): FwLeaderboardsGetVictoryPointsYesterdayInner {
    return FwLeaderboardsGetVictoryPointsYesterdayInnerToJSONTyped(json, false);
}

export function FwLeaderboardsGetVictoryPointsYesterdayInnerToJSONTyped(value?: FwLeaderboardsGetVictoryPointsYesterdayInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'faction_id': value['factionId'],
    };
}

