/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IndustryFacilitiesGetInner
 */
export interface IndustryFacilitiesGetInner {
    /**
     * ID of the facility
     * @type {number}
     * @memberof IndustryFacilitiesGetInner
     */
    facilityId: number;
    /**
     * Owner of the facility
     * @type {number}
     * @memberof IndustryFacilitiesGetInner
     */
    ownerId: number;
    /**
     * Region ID where the facility is
     * @type {number}
     * @memberof IndustryFacilitiesGetInner
     */
    regionId: number;
    /**
     * Solar system ID where the facility is
     * @type {number}
     * @memberof IndustryFacilitiesGetInner
     */
    solarSystemId: number;
    /**
     * Tax imposed by the facility
     * @type {number}
     * @memberof IndustryFacilitiesGetInner
     */
    tax?: number;
    /**
     * Type ID of the facility
     * @type {number}
     * @memberof IndustryFacilitiesGetInner
     */
    typeId: number;
}

/**
 * Check if a given object implements the IndustryFacilitiesGetInner interface.
 */
export function instanceOfIndustryFacilitiesGetInner(value: object): value is IndustryFacilitiesGetInner {
    if ((!('facilityId' in (value as Record<string, any>)) && !('facility_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['facilityId'] === undefined && (value as Record<string, any>)['facility_id'] === undefined)) return false;
    if ((!('ownerId' in (value as Record<string, any>)) && !('owner_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownerId'] === undefined && (value as Record<string, any>)['owner_id'] === undefined)) return false;
    if ((!('regionId' in (value as Record<string, any>)) && !('region_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['regionId'] === undefined && (value as Record<string, any>)['region_id'] === undefined)) return false;
    if ((!('solarSystemId' in (value as Record<string, any>)) && !('solar_system_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['solarSystemId'] === undefined && (value as Record<string, any>)['solar_system_id'] === undefined)) return false;
    if ((!('typeId' in (value as Record<string, any>)) && !('type_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['typeId'] === undefined && (value as Record<string, any>)['type_id'] === undefined)) return false;
    return true;
}

export function IndustryFacilitiesGetInnerFromJSON(json: any): IndustryFacilitiesGetInner {
    return IndustryFacilitiesGetInnerFromJSONTyped(json, false);
}

export function IndustryFacilitiesGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): IndustryFacilitiesGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'facilityId': json['facility_id'],
        'ownerId': json['owner_id'],
        'regionId': json['region_id'],
        'solarSystemId': json['solar_system_id'],
        'tax': json['tax'] == null ? undefined : json['tax'],
        'typeId': json['type_id'],
    };
}

export function IndustryFacilitiesGetInnerToJSON(json: any): IndustryFacilitiesGetInner {
    return IndustryFacilitiesGetInnerToJSONTyped(json, false);
}

export function IndustryFacilitiesGetInnerToJSONTyped(value?: IndustryFacilitiesGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'facility_id': value['facilityId'],
        'owner_id': value['ownerId'],
        'region_id': value['regionId'],
        'solar_system_id': value['solarSystemId'],
        'tax': value['tax'],
        'type_id': value['typeId'],
    };
}

