/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * required_item object
 * @export
 * @interface LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner
 */
export interface LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner {
    /**
     * 
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner
     */
    quantity: number;
    /**
     * 
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner
     */
    typeId: number;
}

/**
 * Check if a given object implements the LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner interface.
 */
export function instanceOfLoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner(value: object): value is LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if ((!('typeId' in (value as Record<string, any>)) && !('type_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['typeId'] === undefined && (value as Record<string, any>)['type_id'] === undefined)) return false;
    return true;
}

export function LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerFromJSON(json: any): LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner {
    return LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerFromJSONTyped(json, false);
}

export function LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'typeId': json['type_id'],
    };
}

export function LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerToJSON(json: any): LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner {
    return LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerToJSONTyped(json, false);
}

export function LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerToJSONTyped(value?: LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'type_id': value['typeId'],
    };
}

