/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner } from './LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner';
import {
    LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerFromJSON,
    LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerFromJSONTyped,
    LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerToJSON,
    LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerToJSONTyped,
} from './LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner';

/**
 * 
 * @export
 * @interface LoyaltyStoresCorporationIdOffersGetInner
 */
export interface LoyaltyStoresCorporationIdOffersGetInner {
    /**
     * Analysis kredit cost
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInner
     */
    akCost?: number;
    /**
     * 
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInner
     */
    iskCost: number;
    /**
     * 
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInner
     */
    lpCost: number;
    /**
     * 
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInner
     */
    offerId: number;
    /**
     * 
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInner
     */
    quantity: number;
    /**
     * 
     * @type {Array<LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner>}
     * @memberof LoyaltyStoresCorporationIdOffersGetInner
     */
    requiredItems: Array<LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInner>;
    /**
     * 
     * @type {number}
     * @memberof LoyaltyStoresCorporationIdOffersGetInner
     */
    typeId: number;
}

/**
 * Check if a given object implements the LoyaltyStoresCorporationIdOffersGetInner interface.
 */
export function instanceOfLoyaltyStoresCorporationIdOffersGetInner(value: object): value is LoyaltyStoresCorporationIdOffersGetInner {
    if ((!('iskCost' in (value as Record<string, any>)) && !('isk_cost' in (value as Record<string, any>))) || ((value as Record<string, any>)['iskCost'] === undefined && (value as Record<string, any>)['isk_cost'] === undefined)) return false;
    if ((!('lpCost' in (value as Record<string, any>)) && !('lp_cost' in (value as Record<string, any>))) || ((value as Record<string, any>)['lpCost'] === undefined && (value as Record<string, any>)['lp_cost'] === undefined)) return false;
    if ((!('offerId' in (value as Record<string, any>)) && !('offer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['offerId'] === undefined && (value as Record<string, any>)['offer_id'] === undefined)) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if ((!('requiredItems' in (value as Record<string, any>)) && !('required_items' in (value as Record<string, any>))) || ((value as Record<string, any>)['requiredItems'] === undefined && (value as Record<string, any>)['required_items'] === undefined)) return false;
    if ((!('typeId' in (value as Record<string, any>)) && !('type_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['typeId'] === undefined && (value as Record<string, any>)['type_id'] === undefined)) return false;
    return true;
}

export function LoyaltyStoresCorporationIdOffersGetInnerFromJSON(json: any): LoyaltyStoresCorporationIdOffersGetInner {
    return LoyaltyStoresCorporationIdOffersGetInnerFromJSONTyped(json, false);
}

export function LoyaltyStoresCorporationIdOffersGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoyaltyStoresCorporationIdOffersGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'akCost': json['ak_cost'] == null ? undefined : json['ak_cost'],
        'iskCost': json['isk_cost'],
        'lpCost': json['lp_cost'],
        'offerId': json['offer_id'],
        'quantity': json['quantity'],
        'requiredItems': ((json['required_items'] as Array<any>).map(LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerFromJSON)),
        'typeId': json['type_id'],
    };
}

export function LoyaltyStoresCorporationIdOffersGetInnerToJSON(json: any): LoyaltyStoresCorporationIdOffersGetInner {
    return LoyaltyStoresCorporationIdOffersGetInnerToJSONTyped(json, false);
}

export function LoyaltyStoresCorporationIdOffersGetInnerToJSONTyped(value?: LoyaltyStoresCorporationIdOffersGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ak_cost': value['akCost'],
        'isk_cost': value['iskCost'],
        'lp_cost': value['lpCost'],
        'offer_id': value['offerId'],
        'quantity': value['quantity'],
        'required_items': ((value['requiredItems'] as Array<any>).map(LoyaltyStoresCorporationIdOffersGetInnerRequiredItemsInnerToJSON)),
        'type_id': value['typeId'],
    };
}

