/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetaCompatibilityDates
 */
export interface MetaCompatibilityDates {
    /**
     * List of compatibility dates.
     * @type {Array<Date>}
     * @memberof MetaCompatibilityDates
     */
    compatibilityDates: Array<Date>;
}

/**
 * Check if a given object implements the MetaCompatibilityDates interface.
 */
export function instanceOfMetaCompatibilityDates(value: object): value is MetaCompatibilityDates {
    if ((!('compatibilityDates' in (value as Record<string, any>)) && !('compatibility_dates' in (value as Record<string, any>))) || ((value as Record<string, any>)['compatibilityDates'] === undefined && (value as Record<string, any>)['compatibility_dates'] === undefined)) return false;
    return true;
}

export function MetaCompatibilityDatesFromJSON(json: any): MetaCompatibilityDates {
    return MetaCompatibilityDatesFromJSONTyped(json, false);
}

export function MetaCompatibilityDatesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaCompatibilityDates {
    if (json == null) {
        return json;
    }
    return {
        
        'compatibilityDates': json['compatibility_dates'],
    };
}

export function MetaCompatibilityDatesToJSON(json: any): MetaCompatibilityDates {
    return MetaCompatibilityDatesToJSONTyped(json, false);
}

export function MetaCompatibilityDatesToJSONTyped(value?: MetaCompatibilityDates | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'compatibility_dates': value['compatibilityDates'],
    };
}

