/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SovereigntyMapGetInner
 */
export interface SovereigntyMapGetInner {
    /**
     * 
     * @type {number}
     * @memberof SovereigntyMapGetInner
     */
    allianceId?: number;
    /**
     * 
     * @type {number}
     * @memberof SovereigntyMapGetInner
     */
    corporationId?: number;
    /**
     * 
     * @type {number}
     * @memberof SovereigntyMapGetInner
     */
    factionId?: number;
    /**
     * 
     * @type {number}
     * @memberof SovereigntyMapGetInner
     */
    systemId: number;
}

/**
 * Check if a given object implements the SovereigntyMapGetInner interface.
 */
export function instanceOfSovereigntyMapGetInner(value: object): value is SovereigntyMapGetInner {
    if ((!('systemId' in (value as Record<string, any>)) && !('system_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['systemId'] === undefined && (value as Record<string, any>)['system_id'] === undefined)) return false;
    return true;
}

export function SovereigntyMapGetInnerFromJSON(json: any): SovereigntyMapGetInner {
    return SovereigntyMapGetInnerFromJSONTyped(json, false);
}

export function SovereigntyMapGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SovereigntyMapGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'allianceId': json['alliance_id'] == null ? undefined : json['alliance_id'],
        'corporationId': json['corporation_id'] == null ? undefined : json['corporation_id'],
        'factionId': json['faction_id'] == null ? undefined : json['faction_id'],
        'systemId': json['system_id'],
    };
}

export function SovereigntyMapGetInnerToJSON(json: any): SovereigntyMapGetInner {
    return SovereigntyMapGetInnerToJSONTyped(json, false);
}

export function SovereigntyMapGetInnerToJSONTyped(value?: SovereigntyMapGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alliance_id': value['allianceId'],
        'corporation_id': value['corporationId'],
        'faction_id': value['factionId'],
        'system_id': value['systemId'],
    };
}

