/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UniverseAncestriesGetInner
 */
export interface UniverseAncestriesGetInner {
    /**
     * The bloodline associated with this ancestry
     * @type {number}
     * @memberof UniverseAncestriesGetInner
     */
    bloodlineId: number;
    /**
     * 
     * @type {string}
     * @memberof UniverseAncestriesGetInner
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof UniverseAncestriesGetInner
     */
    iconId?: number;
    /**
     * 
     * @type {number}
     * @memberof UniverseAncestriesGetInner
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UniverseAncestriesGetInner
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UniverseAncestriesGetInner
     */
    shortDescription?: string;
}

/**
 * Check if a given object implements the UniverseAncestriesGetInner interface.
 */
export function instanceOfUniverseAncestriesGetInner(value: object): value is UniverseAncestriesGetInner {
    if ((!('bloodlineId' in (value as Record<string, any>)) && !('bloodline_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['bloodlineId'] === undefined && (value as Record<string, any>)['bloodline_id'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function UniverseAncestriesGetInnerFromJSON(json: any): UniverseAncestriesGetInner {
    return UniverseAncestriesGetInnerFromJSONTyped(json, false);
}

export function UniverseAncestriesGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UniverseAncestriesGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'bloodlineId': json['bloodline_id'],
        'description': json['description'],
        'iconId': json['icon_id'] == null ? undefined : json['icon_id'],
        'id': json['id'],
        'name': json['name'],
        'shortDescription': json['short_description'] == null ? undefined : json['short_description'],
    };
}

export function UniverseAncestriesGetInnerToJSON(json: any): UniverseAncestriesGetInner {
    return UniverseAncestriesGetInnerToJSONTyped(json, false);
}

export function UniverseAncestriesGetInnerToJSONTyped(value?: UniverseAncestriesGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bloodline_id': value['bloodlineId'],
        'description': value['description'],
        'icon_id': value['iconId'],
        'id': value['id'],
        'name': value['name'],
        'short_description': value['shortDescription'],
    };
}

