/* tslint:disable */
/* eslint-disable */
/**
 * EVE SKINR Ingenuity (ESI) - tranquility
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2020-01-01
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UniverseSystemKillsGetInner
 */
export interface UniverseSystemKillsGetInner {
    /**
     * Number of NPC ships killed in this system
     * @type {number}
     * @memberof UniverseSystemKillsGetInner
     */
    npcKills: number;
    /**
     * Number of pods killed in this system
     * @type {number}
     * @memberof UniverseSystemKillsGetInner
     */
    podKills: number;
    /**
     * Number of player ships killed in this system
     * @type {number}
     * @memberof UniverseSystemKillsGetInner
     */
    shipKills: number;
    /**
     * 
     * @type {number}
     * @memberof UniverseSystemKillsGetInner
     */
    systemId: number;
}

/**
 * Check if a given object implements the UniverseSystemKillsGetInner interface.
 */
export function instanceOfUniverseSystemKillsGetInner(value: object): value is UniverseSystemKillsGetInner {
    if ((!('npcKills' in (value as Record<string, any>)) && !('npc_kills' in (value as Record<string, any>))) || ((value as Record<string, any>)['npcKills'] === undefined && (value as Record<string, any>)['npc_kills'] === undefined)) return false;
    if ((!('podKills' in (value as Record<string, any>)) && !('pod_kills' in (value as Record<string, any>))) || ((value as Record<string, any>)['podKills'] === undefined && (value as Record<string, any>)['pod_kills'] === undefined)) return false;
    if ((!('shipKills' in (value as Record<string, any>)) && !('ship_kills' in (value as Record<string, any>))) || ((value as Record<string, any>)['shipKills'] === undefined && (value as Record<string, any>)['ship_kills'] === undefined)) return false;
    if ((!('systemId' in (value as Record<string, any>)) && !('system_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['systemId'] === undefined && (value as Record<string, any>)['system_id'] === undefined)) return false;
    return true;
}

export function UniverseSystemKillsGetInnerFromJSON(json: any): UniverseSystemKillsGetInner {
    return UniverseSystemKillsGetInnerFromJSONTyped(json, false);
}

export function UniverseSystemKillsGetInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): UniverseSystemKillsGetInner {
    if (json == null) {
        return json;
    }
    return {
        
        'npcKills': json['npc_kills'],
        'podKills': json['pod_kills'],
        'shipKills': json['ship_kills'],
        'systemId': json['system_id'],
    };
}

export function UniverseSystemKillsGetInnerToJSON(json: any): UniverseSystemKillsGetInner {
    return UniverseSystemKillsGetInnerToJSONTyped(json, false);
}

export function UniverseSystemKillsGetInnerToJSONTyped(value?: UniverseSystemKillsGetInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'npc_kills': value['npcKills'],
        'pod_kills': value['podKills'],
        'ship_kills': value['shipKills'],
        'system_id': value['systemId'],
    };
}

